18F/guides-style

lib/guides_style_18f/includes/analytics.html
This changes the DAP embed code to:
```
<script id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA"></script>
```
This takes advantage of the DAP's new [centrally hosted JavaScript code](https://www.digitalgov.gov/2015/08/14/secure-central-hosting-for-the-digital-analytics-program/), which means 18f.gsa.gov will automatically get security updates, new features, and other bugfixes automatically.
I also updated the GA snippet:
* to use `forceSSL` and to remove the protocol-relative URL
* changed `gsa.gov` to `auto` when setting the property ID.
=> Update to new DAP snippet, add forceSSL

lib/guides_style_18f/navigation.rb, lib/guides_style_18f/repository.rb, test/repository_test.rb
Once this goes in, I'll issue a PR to update 18F/guides-template, to include the updated `guides_style_18f` gem, to use the new `go_script` gem, and to update the guide instructions. Then I'll be eager to see how easy a time @kategarklavs, @wslack, @emileighoutlaw, @melodykramer, @awfrancisco, and whoever else has trying to create and publish a new guide.
I can tell you, running locally, it's pretty _sweeet_...
cc: @arowla @afeld @gboone
=> Make `create_repo` command robust, well-tested

lib/guides_style_18f/includes/sidebar.html
... not the parent's
This should really have a test, but the only way I can see to do that is to move the URL forming logic from templates into code, and that's a bigger change than I want to make right now/ without @mbland weighing in.
=> Make child links respect the child `internal` attr

lib/guides_style_18f/sass/_guides_style_18f_main.scss
This changes the overflow to auto to prevent the scroll bar from appearing in the sidenav.
Fixes this: https://github.com/18F/methods/pull/71#issuecomment-150339342
=> Fix scroll bug on sidebar navigation

lib/guides_style_18f/includes/footer.html
Closes #15.
The footer now appears as:
cc: @ultrasaurus @gbinal @emileighoutlaw
=> Add repository link to footer

lib/guides_style_18f/includes/scripts.html
Fixes #18 
Longer term, I *highly* recommend we move away from CDN and towards hosting jQuery from the repo instead. I think this expands beyond to scope of this issue and have opened another issue for the team to take into consideration.
**Move jQuery from CDN to self hosted in repo**
https://github.com/18F/guides-style/issues/19
Also reference https://github.com/18F/pages/issues/53 where @mbland debugged the original issue.
=> Removing async attr from script tags in lib/includes/scripts.html

lib/guides_style_18f/sass/_guides_style_18f_main.scss
This fixes the sidebar nav styling so that the blue line aligns with the left edge.
This is what it looks like now:
This is what it looks like before:
Note: I wasn't able to test this locally so please verify this works as intended @mbland.
=> Fix styling of sidebar nav line

lib/guides_style_18f/sass/_guides_style_18f_main.scss
This removes min-height from media queries to prevent the mobile collapsing when the vertical height is smaller.
Note: @mbland I wasn't able to test this locally so please test to make sure it works as intended.
=> Update media queries to remove min height

lib/guides_style_18f/navigation.rb, test/_pages/add-a-new-page/make-a-child-page.md, test/_pages/update-the-config-file/understanding-baseurl.md, test/navigation_test.rb
After #26, I realized that there's no need to require the `parent:` front matter, as it's possible to compute parent-child relationships using `permalink:` values. This completely replaces the earlier implementation that was based on matching `parent:` with the `text:` of other `navigation:` items, but passes all of the earlier tests (with one tweak to `test_should_raise_if_parent_page_does_not_exist`). Added the new `test_do_not_remove_external_page_entries`, moved another test, and slightly refactored another.
cc: @ccostino @ertzeid
=> Build nav based on permalinks, not `parent` titles

lib/guides_style_18f/navigation.rb, lib/guides_style_18f/repository.rb, test/navigation_test.rb
Addresses item noted in 18F/guides-template#68.
Note that the bulk of the changes to `navigation.rb` are indentations after creating the `NavigationData` module. The _real_ new code is `remove_stale_children`, called from `remove_stale_nav_entries`.
cc: @ccostino @ertzeid @emileighoutlaw
=> Remove new images.png, recursively remove child nav items

README.md, lib/guides_style_18f/includes/sidebar-children.html, lib/guides_style_18f/includes/sidebar.html, lib/guides_style_18f/navigation.rb, lib/guides_style_18f/tags.rb, test/navigation_test.rb, test/tags_test.rb
Closes #31.
#30 should go in before this one.
This does two things:
- Supports `navtitle:` front matter that allows for alternate text in the nav bar.
- Adds the `expand_nav:` site variable (in `_config.yml`) that, when set to `true`, will expand all of the nav bar entries.
cc: @afeld @leahbannon @ccostino @ertzeid
=> Support short nav titles, expanded nav bar

README.md, lib/guides_style_18f/includes/sidebar-children.html, lib/guides_style_18f/tags.rb, test/tags_test.rb
Closes 18F/pages#54.
This allows individual navigation bar items to be expanded or contracted, overriding the default provided by the top-level `expand_nav:` property.
cc: @afeld @brittag
=> `expand_nav:` per `navigation:` item

lib/guides_style_18f/sass/_guides_style_18f_main.scss
Addresses an issue from #22. Just noticed that the existing style forces small images to stretch; see the example below from https://pages.18f.gov/guides-template/post-your-guide/#set-default-branch. This change seems to address the issue, yet larger images remain responsive.
cc: @juliaelman @maya 
---
---
---
=> Don't stretch small images beyond their width

lib/guides_style_18f.rb, lib/guides_style_18f/breadcrumbs.rb, lib/guides_style_18f/generator.rb, lib/guides_style_18f/includes/breadcrumbs.html, lib/guides_style_18f/navigation.rb, test/breadcrumbs_test.rb, test/navigation_test.rb
Uses the `navigation:` data (generated by `./go update_nav` and stored in `_config.yml`) to produce a mapping from page URL to a list of breadcrumb objects. `Generator.generate` attaches this data to each page, and the `includes/breadcrumbs.html` template renders it as an unordered list.
The breadcrumbs are not yet included and styled in the standard layout, but can be included using the following Liquid directive:
```
{% guides_style_18f_include breadcrumbs.html %}
```
Also includes a test fix for newer versions of Jekyll, which will now provide a default `title:` property for a page based on its URL slug if a `title:` isn't specified in the page's front matter.
cc: @andrewmaier @ccostino @ertzeid @mtorres253 
Also cc: @catherinedevlin and @DavidEBest, in case you feel like picking up …
=> Breadcrumb implementation

lib/guides_style_18f/breadcrumbs.rb, lib/guides_style_18f/generator.rb, lib/guides_style_18f/namespace_flattener.rb, test/breadcrumbs_test.rb, test/dummy_collection.rb, test/dummy_page.rb, test/dummy_site.rb, test/flatten_url_namespace_test.rb
This enables documents to be structured hierarchically in the `_pages` directory, yet have their URLs and breadcrumbs all be rooted at `{{ site.baseurl }}` rather than maintaining a hierarchical URL structure. It is enabled by setting `flat_namespace: true` in `_config.yml`. It performs collision checking, i.e. enabling this with a structure that contains `/foo/bar/` and `/baz/bar/` will raise an error, since both URLs map to `/bar/`.
cc: @ccostino @ertzeid @andrewmaier @mtorres253
=> Implement and test flat URL namespacing

lib/guides_style_18f/breadcrumbs.rb, lib/guides_style_18f/generated_pages.rb, lib/guides_style_18f/generator.rb, lib/guides_style_18f/includes/home-redirect.html, lib/guides_style_18f/layouts.rb, lib/guides_style_18f/layouts/generated/home-redirect.html, lib/guides_style_18f/namespace_flattener.rb
Based on #45 and #46, which must go in first. Will create a corresponding 18F/handbook PR that, when combined with the changes in this branch, produce a functional Handbook site where all page URLs are direct children of `site.baseurl` and the pages generated from generated `navigation:` items will redirect to a URL fragment on the home page.
Note that as I originally write this, #45 and #46 have automated tests, but I need to add tests for the changes added in this PR.
cc: @andrewmaier @ccostino @ertzeid @mtorres253
=> [WIP] Generate navigation pages that redirect to home page IDs

assets/js/18f-guide.js, assets/js/vendor/private-eye-1.0.0.js, lib/guides_style_18f/includes/header.html, lib/guides_style_18f/includes/scripts.html
Re-adds the old version of private-eye back in, which will allow us to revert https://github.com/18F/guides-template/pull/82 without breaking sites using version <= 0.4.3 of this gem. Basically, without https://github.com/18F/pages-server/issues/55 being done, we can't remove/change any asset paths in this repository.
/cc @wslack
=> fix for private-eye

lib/guides_style_18f/sass/_guides_style_18f_main.scss
Another fix for: https://github.com/18F/frontend/issues/111
* Sets max-height to a very high number so it animates properly when opening/closing the sidenav menu
=> resets max height at a high number to preserve animation

lib/guides_style_18f/includes/header.html
In other words, fix clicking the logo not actually taking you to the `baseurl`.
=> remove duplicate href attribute in homepage link

lib/guides_style_18f/repository.rb, test/repository_test.rb
This commit removes the creation of the 18f-pages branch from the `create_new_git_repository`. Now that Federalist is the new home for 18F Pages, there is no need to create this branch.
Ref 18F/guides-template#90
=> Remove 18f-pages branch creation

lib/guides_style_18f/includes/banner.html, lib/guides_style_18f/includes/footer.html, lib/guides_style_18f/layouts/default.html
Two HTML fixes, as noted by #91:
- Changed USA banner element to a div instead of a header to avoid nested header error
- Added missing closing div tag
The complaint about an open script tag is invalid, as there is a closing script tag after the GA JS block. If there are thoughts about how to get the linter to not throw an error, I'd love to hear 'em!
=> Header/footer HTML fixes

lib/guides_style_18f/version.rb
because 1.0.1 was already taken :woman_facepalming:
=> bump to 1.0.2

lib/guides_style_18f/includes/head.html
Fixes #98. I think maybe the icons `<link>`s were probably just accidentally commented out, but I'm unsure.
=> Uncomment the markup that links favicons/icons

lib/guides_style_18f/includes/scripts.html
Fixes #96
This PR amends `scripts.html` to include `jekyll_pages_api_search`'s javascript assets only if the site has defined settings for `jekyll_pages_api_search` in its configuration (ie, in `_config.yml`).
This alleviates the missing `search-bundle.js` `404` that gets thrown when a site has not configured `jekyll_pages_api_search`.
=> Only include search assets if site has configured jekyll_pages_api_search

assets/js/18f-guide.js
Note that this list contains some hostnames that are no longer in use, just in case they are still linked to from one of the guides. Follow-up task:
=> update list of internal URLs

guides-style-18f.gemspec
Since `pages.18f.gov` is retired.
=> Update guides-template URL

README.md, lib/guides_style_18f/includes/header.html, lib/guides_style_18f/includes/scripts.html
Closes #108.
Also documented usage of [jekyll_pages_api_search](https://github.com/18F/jekyll_pages_api_search).
/cc https://github.com/18F/federalist-docs/pull/142
=> add support for search.gov

lib/guides_style_18f/sass/_guides_style_18f_main.scss
The large size and animated push-in effect on the sidebar links was distracting and didn't fit with the type scale of the rest of the page. I modified the link style so the blue bar would animate, but not push in the text, and I reduced the size of the link text and tightened the leading to read more smoothly, especially when the sidebar text breaks over multiple lines.
=> Simplify size and animation of sidebar links

guides-style-18f.gemspec, lib/guides_style_18f/version.rb
Didn't realize this was broken until the gem was published. Tested by locally building then installing the gem.
=> fix files included in the gem
